/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;

import BTL.bussiness.BrandsDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import BTL.entity.Brands;
/**
 *
 * @author admin
 */
public class BrandFrom extends javax.swing.JPanel {

    private BrandsDao brandDao = new BTL.bussiness.BrandsDao();
    private DefaultTableModel model;
    private final MainForm mainForm;
    public BrandFrom(MainForm mainForm) {
        initComponents();
        this.mainForm=mainForm;
        initTable();
        loadData();
    }
    public void reset(){
        txtNameBrand.setText("");
        txtOriginBrand.setText("");
        txtTimKiem.setText("");
        // Xóa dòng cboLoc nếu không có component này
        loadData();

    }

    // 2. HÀM TẠO CỘT CHO BẢNG
    private void initTable() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID", "Tên Thương Hiệu", "Xuất Xứ"});
        tblBrandList.setModel(model);
    }

    // 3. HÀM ĐỔ DỮ LIỆU TỪ CSDL VÀO BẢNG
    private void loadData() {
        model.setRowCount(0);
        
        List<Brands> list = brandDao.getall(); 
        for (Brands b : list) {
         
            model.addRow(new Object[]{ b.getBrandId(), b.getName(), b.getOrigin() });
        }
    }
    // Hàm này sẽ được gọi khi bấm nút Tìm
     private void searchBrand() {
        String keyword = txtTimKiem.getText().trim().toLowerCase();
        model.setRowCount(0);
        List<Brands> list = brandDao.getall();
        for (Brands b : list) {
            if (b.getName().toLowerCase().contains(keyword) || 
                (b.getOrigin() != null && b.getOrigin().toLowerCase().contains(keyword))) {
                model.addRow(new Object[]{ b.getBrandId(), b.getName(), b.getOrigin() });
            }
        }
    }
    /**
     * Creates new form BrandFrom
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrandList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtNameBrand = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtOriginBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 225));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("QUẢN LÝ THƯƠNG HIỆU");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tblBrandList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Thương Hiệu", "Xuất Xứ"
            }
        ));
        tblBrandList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrandListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrandList);

        jLabel1.setText("Tên thương hiệu:");
        jLabel1.setToolTipText("");

        txtNameBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameBrandActionPerformed(evt);
            }
        });

        jLabel2.setText("Xuất xứ:");

        txtOriginBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOriginBrandActionPerformed(evt);
            }
        });

        jLabel3.setText("Nhập:");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(77, 77, 77)
                        .addComponent(btnSua))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtOriginBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnLamMoi)
                        .addGap(76, 76, 76))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnTimKiem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNameBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtOriginBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
    txtNameBrand.setText("");
        txtOriginBrand.setText("");
        txtTimKiem.setText("");
        // Xóa dòng cboLoc nếu không có component này
        loadData();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    // 1. Kiểm tra xem có chọn dòng nào chưa
    int row = tblBrandList.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa!");
        return;
    }
    
    try {
        // 2. Lấy ID từ cột đầu tiên (Cột 0) của dòng đang chọn
        int id = Integer.parseInt(tblBrandList.getValueAt(row, 0).toString());
        
        // 3. Tạo đối tượng mới với thông tin đã sửa từ ô nhập
        BTL.entity.Brands b = new BTL.entity.Brands(id, txtNameBrand.getText().trim(), txtOriginBrand.getText().trim());
        
        // 4. Gọi hàm Update
        if (brandDao.update(b)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadData(); // Load lại bảng
            
            // Xóa trắng form cho sạch
            txtNameBrand.setText("");
            txtOriginBrand.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtOriginBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOriginBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOriginBrandActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
// Code cho nút THÊM
    if (txtNameBrand.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Chưa nhập tên thương hiệu!");
        return;
    }
    
    // Tạo đối tượng Brand (ID = 0)
    BTL.entity.Brands b = new BTL.entity.Brands(0, txtNameBrand.getText().trim(), txtOriginBrand.getText().trim());
    
    if (brandDao.insert(b) > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
        loadData(); // Load lại bảng ngay lập tức
        
        // Xóa trắng ô nhập
        txtNameBrand.setText(""); 
        txtOriginBrand.setText(""); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Thêm thất bại!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
// 1. Kiểm tra chọn dòng
    int row = tblBrandList.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa!");
        return;
    }
    
    // 2. Hỏi xác nhận (Tránh xóa nhầm)
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 3. Lấy ID và xóa
        int id = Integer.parseInt(tblBrandList.getValueAt(row, 0).toString());
        
        if (brandDao.delete(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
            loadData(); // Load lại bảng
            
            // Xóa trắng form
            txtNameBrand.setText("");
            txtOriginBrand.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblBrandListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandListMouseClicked
    int row = tblBrandList.getSelectedRow();
    if (row >= 0) {
        // Cột 1 là Tên, Cột 2 là Xuất xứ (Cột 0 là ID ẩn không cần hiện)
        txtNameBrand.setText(tblBrandList.getValueAt(row, 1).toString());
        
        Object origin = tblBrandList.getValueAt(row, 2);
        txtOriginBrand.setText(origin != null ? origin.toString() : "");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblBrandListMouseClicked

    private void txtNameBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameBrandActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
// Lấy từ khóa người dùng nhập
    String keyword = txtTimKiem.getText().toLowerCase();
    
    // Xóa bảng hiện tại
    model.setRowCount(0);
    
    // Duyệt qua danh sách gốc và lọc
    for (BTL.entity.Brands b : brandDao.getall()) {
        if (b.getName().toLowerCase().contains(keyword) || 
            b.getOrigin().toLowerCase().contains(keyword)) {
            model.addRow(new Object[]{ b.getBrandId(), b.getName(), b.getOrigin() });
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
    searchBrand();     // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:if (evt.getKeyCode() == 10) { // Số 10 là mã phím Enter
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblBrandList;
    private javax.swing.JTextField txtNameBrand;
    private javax.swing.JTextField txtOriginBrand;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
