/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;

import BTL.bussiness.CartDao;
import BTL.entity.Users;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CartForm extends javax.swing.JPanel {
    private final CustomersForm customersForm;
    private javax.swing.table.DefaultTableModel tblModel;
    private final Users users;
    private double totalCartAmount = 0;
    private int currentUserId;
    /**
     * Creates new form CartForm
     */
    public CartForm(CustomersForm customersForm, Users users) {
        initComponents();
        this.customersForm = customersForm;
        this.users = users; // ĐÃ SỬA: Gán giá trị để không bị lỗi "not initialized"
        this.currentUserId = users.getUserId(); 

        tblModel = new javax.swing.table.DefaultTableModel();
        // Định nghĩa 5 cột: ID (ẩn), Tên, Số lượng, Đơn giá, Thành tiền
        tblModel.setColumnIdentifiers(new String[]{"ID", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Thành Tiền"});
        
        jTable1.setModel(tblModel);

        // Ẩn cột ID (index 0)
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);

        loadCartData(this.currentUserId);
    }
    private void updateTotalAmount() {
        double total = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            double rowTotal = Double.parseDouble(jTable1.getValueAt(i, 4).toString());
            total += rowTotal;
        }
        this.totalCartAmount = total; 
        // lblTotal.setText(String.format("%,.0f VNĐ", total));
}
    CartDao cartDao = new BTL.bussiness.CartDao();

    public void loadCartData(int userId) {
            tblModel.setRowCount(0);
            List<BTL.entity.Cart> list = cartDao.getByUser(userId);

            for (BTL.entity.Cart c : list) {
                double unitPrice = c.getPrice();
                int quantity = c.getQuantity();
                double lineTotal = quantity * unitPrice;

                tblModel.addRow(new Object[]{
                    c.getProductId(),
                    c.getProductName(),
                    quantity,
                    (long) unitPrice,
                    (long) lineTotal
                });
            }
            updateTotalAmount();
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Giỏ Hàng");

        btnadd.setText("Thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndel.setText("Xóa");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(108, 108, 108)
                .addComponent(btndel)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btndel))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa!");
            return;
        }

        Object value = jTable1.getValueAt(row, 0);
        if (value == null) return;

        try {
            int productId = Integer.parseInt(value.toString());
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                if (cartDao.deleteByUserAndProduct(currentUserId, productId)) {
                    loadCartData(currentUserId);
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
                }
            }
        } catch (NumberFormatException e) {
            System.out.println("Lỗi định dạng ID: " + e.getMessage());
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if (jTable1.getRowCount() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Giỏ hàng đang trống!");
        return;
    }

    String address = javax.swing.JOptionPane.showInputDialog(this, "Nhập địa chỉ giao hàng:");
    if (address == null || address.trim().isEmpty()) return;

    String customerName = users.getFullName(); 

    // 1. Thực hiện đặt hàng
    boolean success = cartDao.checkout(currentUserId, address, "COD", customerName);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Đặt hàng thành công!");
        
        // 2. LẤY ID ĐƠN HÀNG VỪA TẠO (Quan trọng)
        // Bạn cần một hàm trong OrdersDao để lấy ID đơn hàng mới nhất của User này
        BTL.bussiness.OrdersDao ordersDao = new BTL.bussiness.OrdersDao();
        int newOrderId = -1;
        
        // Lấy danh sách đơn hàng của user, tìm cái ID lớn nhất (mới nhất)
        List<BTL.entity.Orders> userOrders = ordersDao.getall(); // Hoặc viết hàm getByUserId
        for(BTL.entity.Orders o : userOrders) {
            if(o.getUserId() == currentUserId && o.getOrderId() > newOrderId) {
                newOrderId = o.getOrderId();
            }
        }

        if (newOrderId != -1) {
            // 3. CHUYỂN SANG TRANG HÓA ĐƠN VÀ ĐỔ DỮ LIỆU
            OrderCus invoice = new OrderCus(this.customersForm);
            invoice.showInvoice(customerName, newOrderId); // Gọi hàm đổ dữ liệu bạn đã viết
            
            // Hiển thị lên giao diện chính
            customersForm.showPanel(invoice, new javax.swing.JButton());
        }

        loadCartData(currentUserId); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi đặt hàng!");
    }
    }//GEN-LAST:event_btnaddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
