/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL.view;

import BTL.entity.Users;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author vanminh
 */
public class MainForm extends javax.swing.JFrame {
    
    private Users currentUser;
    private HomePage homePage;
    private StaffCRUD customerCRUD;
    private SuppliersCRUD suppliersCRUD;
    private Account account;
    private OrdersForm ordersForm;
    private NotificationCRUD notificationCRUD;
    private StatisticalCRUD statisticalCRUD;
    private ProductForm productForm;
    private CateCRUD cateCRUD;
    private BrandFrom brandFrom;
    public MainForm(Users user) {
        this.currentUser = user;
        initComponents();
        checkPermissions();
        setHomePage();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    private void showPanel(JPanel panel, JButton btn) {
        resetbtn();
        btn.setBackground(new Color(77, 120, 204));
        jplfill2.removeAll();
        jplfill2.add(panel);
        jplfill2.revalidate();
        jplfill2.repaint();
    }
    public void setHomePage(){
        if(homePage == null){
            homePage = new HomePage(this);
        }
        showPanel(homePage, btnTrangchu);
    }
    public void setcustomerCRUD(){
        if(customerCRUD == null){
            customerCRUD = new StaffCRUD(this);
        }
        showPanel(customerCRUD, btnStaff);
    }
    public void setsuppliersCRUD(){
        if(suppliersCRUD == null){
            suppliersCRUD = new SuppliersCRUD(this);
        }
        showPanel(suppliersCRUD, btnSuppliers);
    }
    public void setOrderForm(){
        if(ordersForm == null){
            ordersForm = new OrdersForm(this);
        }
        showPanel(ordersForm, btnOrder);
    }
    public void setNotificationCRUD(){
        if(notificationCRUD == null){
            notificationCRUD = new NotificationCRUD(this, this.currentUser);
        }
        showPanel(notificationCRUD, btnNotification);
    }
    public void setStatisticalCRUD(){
        if(statisticalCRUD == null){
            statisticalCRUD = new StatisticalCRUD(this);
        }
        showPanel(statisticalCRUD, btnSatistical);
    }
    public void setcateForm(){
        if(cateCRUD == null){
            cateCRUD = new CateCRUD(this);
        }
        showPanel(cateCRUD, btnCategory);
    }
    public void setbrandsForm(){
        if(brandFrom == null){
            brandFrom = new BrandFrom(this);
        }
        showPanel(brandFrom, btnBrands);
    }
    public void setupAccount(){
        if(account == null){
            account = new Account(this);
        }
        account.setProfileData(this.currentUser);
        showPanel(account, btnTk);
    }
    private void checkPermissions() {
        String role = currentUser.getRole().trim();
        String Name = currentUser.getFullName().trim();
        
        System.out.println("DEBUG - Role hien tai: [" + role + "]");
        
        if (role.equalsIgnoreCase("staff")) {
            txtName.setText(Name);
            txtRole.setText(role);
            btnStaff.setVisible(false);
            btnSuppliers.setVisible(false);
            btnBrands.setVisible(false);
        } else if (role.equalsIgnoreCase("admin")) {
            txtName.setText(Name);
            txtRole.setText(role);
            btnStaff.setEnabled(true);
            btnSuppliers.setEnabled(true);
            btnBrands.setEnabled(true);
        }
    }
    public void resetbtn(){
        btnTrangchu.setBackground(new Color(255,255,255));
        btnCategory.setBackground(new Color(255,255,255));
        btnProduct.setBackground(new Color(255,255,255));
        btnBrands.setBackground(new Color(255,255,255));
        btnStaff.setBackground(new Color(255,255,255));
        btnOrder.setBackground(new Color(255,255,255));
        btnNotification.setBackground(new Color(255,255,255));
        btnSatistical.setBackground(new Color(255,255,255));
        btnSuppliers.setBackground(new Color(255,255,255));
        btnTk.setBackground(new Color(255,255,255));
    }
    public void showProductByCategory(int catId, String catName) {
        // 1. Tạo mới ProductForm
        if (productForm == null) {
            productForm = new ProductForm();
        }

        // 2. Gọi hàm lọc vừa viết ở Bước 1
        productForm.filterByCategory(catId, catName);

        // 3. Hiển thị lên màn hình (Dùng lại hàm showPanel có sẵn của bạn)
        showPanel(productForm, btnProduct);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTrangchu = new javax.swing.JButton();
        btnProduct = new javax.swing.JButton();
        btnCategory = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnNotification = new javax.swing.JButton();
        btnSatistical = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtRole = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnTk = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnBrands = new javax.swing.JButton();
        jplfill2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));

        btnTrangchu.setText("Trang chủ");
        btnTrangchu.setBorderPainted(false);
        btnTrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangchuActionPerformed(evt);
            }
        });

        btnProduct.setText("Sản Phẩm");
        btnProduct.setBorderPainted(false);
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        btnCategory.setText("Danh mục");
        btnCategory.setBorderPainted(false);
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        btnOrder.setText("Hóa đơn");
        btnOrder.setBorderPainted(false);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnStaff.setText("Nhân viên");
        btnStaff.setBorderPainted(false);
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnNotification.setText("Thông báo");
        btnNotification.setBorderPainted(false);
        btnNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificationActionPerformed(evt);
            }
        });

        btnSatistical.setText("Thống kê");
        btnSatistical.setBorderPainted(false);
        btnSatistical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisticalActionPerformed(evt);
            }
        });

        btnLogout.setText("Đăng xuất");
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtName.setBorder(null);

        txtRole.setEditable(false);
        txtRole.setBackground(new java.awt.Color(255, 255, 255));
        txtRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtRole.setForeground(new java.awt.Color(102, 102, 102));
        txtRole.setBorder(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vanminh\\Documents\\NetBeansProjects\\study\\src\\icon\\man.png")); // NOI18N

        btnTk.setText("Tài khoản");
        btnTk.setBorderPainted(false);
        btnTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTkActionPerformed(evt);
            }
        });

        btnSuppliers.setText("Nhà cung cấp");
        btnSuppliers.setBorderPainted(false);
        btnSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppliersActionPerformed(evt);
            }
        });

        btnBrands.setText("Thương hiệu");
        btnBrands.setBorderPainted(false);
        btnBrands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSatistical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtRole))
                .addContainerGap())
            .addComponent(btnBrands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSatistical, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrands, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnTk, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jplfill2.setBackground(new java.awt.Color(255, 255, 255));
        jplfill2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jplfill2.setPreferredSize(new java.awt.Dimension(600, 600));
        jplfill2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jplfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addComponent(jplfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangchuActionPerformed
        // TODO add your handling code here:
        setHomePage();
        homePage.reset();
    }//GEN-LAST:event_btnTrangchuActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        // TODO add your handling code here:
        setcustomerCRUD();
        customerCRUD.reset();
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppliersActionPerformed
        // TODO add your handling code here:
        setsuppliersCRUD();
        suppliersCRUD.reset();
    }//GEN-LAST:event_btnSuppliersActionPerformed

    private void btnTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTkActionPerformed
        // TODO add your handling code here:
        setupAccount();
    }//GEN-LAST:event_btnTkActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        setOrderForm();
        ordersForm.reset();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificationActionPerformed
        // TODO add your handling code here:
        setNotificationCRUD();
        notificationCRUD.reset();
    }//GEN-LAST:event_btnNotificationActionPerformed

    private void btnSatisticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisticalActionPerformed
        // TODO add your handling code here:
        setStatisticalCRUD();
        statisticalCRUD.reset();
    }//GEN-LAST:event_btnSatisticalActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        // TODO add your handling code here:
        System.out.println("--- Bắt đầu mở trang Sản phẩm ---");
        try {
            // 1. Kiểm tra khởi tạo
            if (productForm == null) {
                System.out.println("Đang khởi tạo ProductForm mới...");
                productForm = new ProductForm();
            }

            // 2. Gọi hàm hiển thị
            System.out.println("Đang gọi showPanel...");
            showPanel(productForm, btnProduct);

            System.out.println("--- Thành công! ---");

        } catch (Exception e) {
            // Nếu có lỗi ngầm, nó sẽ hiện thông báo lên màn hình cho bạn biết
            e.printStackTrace(); // In chi tiết lỗi xuống cửa sổ Output bên dưới
            javax.swing.JOptionPane.showMessageDialog(this, "Lỗi không mở được trang Sản phẩm:\n" + e.getMessage());
        }
        productForm.refreshData();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        // TODO add your handling code here:
        setcateForm();
        cateCRUD.reset();
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnBrandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandsActionPerformed
        // TODO add your handling code here:
        setbrandsForm();
        brandFrom.reset();
    }//GEN-LAST:event_btnBrandsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainForm(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrands;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotification;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnSatistical;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JButton btnTk;
    private javax.swing.JButton btnTrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jplfill2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
