/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;
import BTL.bussiness.NotificationDao;
import BTL.entity.Notification;
import BTL.entity.Users;
import java.io.File;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author Administrator
 */
public class NotificationCRUD extends javax.swing.JPanel {
    
    private DefaultTableModel tableModel;
    private final NotificationDao dao = new NotificationDao();
    private Users currentUser;
    // Lưu ID dòng đang chọn và đường dẫn ảnh
    private int selectedId = -1;
    private final MainForm mainForm;
    private String currentImagePath = "";
    /**
     * Creates new form NotificationCRUD
     */
    public NotificationCRUD(MainForm mainForm, Users user) {
        this.currentUser = user;
        this.mainForm = mainForm;
        initComponents();
        initTable();
        loadTable();
        initTableEvent();
        
    }
    public void reset(){
        txtTitle.setText("");
        txtMessage.setText("");
        dao.delete(selectedId);
        loadTable();
        resetForm();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        btnImage = new javax.swing.JButton();
        lblPreview = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Thông Báo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tiêu đề :");

        jLabel3.setText("Nội dung:");

        jLabel4.setText("Ảnh:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnLammoi.setText("Làm mới");
        btnLammoi.addActionListener(this::btnLammoiActionPerformed);

        btnImage.setText("Chọn file");
        btnImage.addActionListener(this::btnImageActionPerformed);

        txtMessage.setColumns(20);
        txtMessage.setLineWrap(true);
        txtMessage.setRows(5);
        txtMessage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSua)
                        .addGap(79, 79, 79)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLammoi)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(44, 44, 44)
                                        .addComponent(btnImage))
                                    .addComponent(lblPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnImage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(lblPreview, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLammoi))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void initTable(){
            tableModel = new DefaultTableModel(
            new Object[]{"ID", "Tiêu đề", "Nội dung", "Đường dẫn ảnh"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(tableModel);

        // Ẩn cột ID để giao diện đẹp hơn
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }      
    private void loadTable() {
        tableModel.setRowCount(0);
        try {
            List<Notification> list = dao.getall(); // Kiểm tra nếu DAO dùng getAll() thì sửa lại chữ A
            for (Notification n : list) {
                tableModel.addRow(new Object[]{
                    n.getNotificationId(),
                    n.getTitle(),
                    n.getMessage(),
                    n.getImage()
                });
            }
        } catch (Exception e) {
            System.out.println("Lỗi load bảng: " + e.getMessage());
        }
    }
    
    
    private void initTableEvent() {
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            int row = jTable1.getSelectedRow();
            if (row >= 0) {
                selectedId = (int) jTable1.getValueAt(row, 0);
                txtTitle.setText(jTable1.getValueAt(row, 1).toString());
                txtMessage.setText(jTable1.getValueAt(row, 2).toString());
                // Lấy đường dẫn ảnh từ bảng gán vào biến tạm
                currentImagePath = jTable1.getValueAt(row, 3) != null ? jTable1.getValueAt(row, 3).toString() : "";
                updatePreviewImage(currentImagePath);
            }
        });
    }
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa!");
        return;
    }

    Notification n = new Notification();
    n.setNotificationId(selectedId);
    n.setTitle(txtTitle.getText());
    n.setMessage(txtMessage.getText());
    n.setImage(currentImagePath);
    
    // PHẢI CÓ DÒNG NÀY ĐỂ TRUYỀN ID NGƯỜI DÙNG VÀO DATABASE
    if (currentUser != null) {
        n.setUserId(currentUser.getUserId()); 
    } else {
        // Nếu currentUser null, lấy đại ID = 1 (admin) để không lỗi DB khi test
        n.setUserId(1); 
    }

    dao.update(n);
    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    loadTable();
    resetForm();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtTitle.getText().isEmpty() || txtMessage.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ tiêu đề và nội dung!");
        return;
    }

    Notification n = new Notification();
    n.setTitle(txtTitle.getText());
    n.setMessage(txtMessage.getText());
    n.setImage(currentImagePath);
    
    
    if (currentUser != null) {
        n.setUserId(currentUser.getUserId()); 
    }
    
    try {
        dao.insert(n);
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
        loadTable();
        resetForm();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm: " + e.getMessage());
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dao.delete(selectedId);
            loadTable();
            resetForm();
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    
    
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
    JFileChooser fileChooser = new JFileChooser();
    javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter("Hình ảnh", "jpg", "png", "gif");
    fileChooser.setFileFilter(filter);
    fileChooser.setAcceptAllFileFilterUsed(false);
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        currentImagePath = fileChooser.getSelectedFile().getAbsolutePath();                
        updatePreviewImage(currentImagePath);        
        JOptionPane.showMessageDialog(this, "Đã chọn ảnh: " + fileChooser.getSelectedFile().getName());
    }
    }//GEN-LAST:event_btnImageActionPerformed
    
    private void updatePreviewImage(String path) {
    
    if (path == null || path.trim().isEmpty()) {
        lblPreview.setIcon(null);
        lblPreview.setText(""); 
        return;
    }

    try {
        File file = new File(path);
        
        if (!file.exists()) {
            lblPreview.setIcon(null);
            lblPreview.setText("");
            return;
        }

        //  Nếu file tồn tại, tiến hành Resize và hiển thị
        ImageIcon icon = new ImageIcon(path);
        java.awt.Image img = icon.getImage();
        
        int w = lblPreview.getWidth() > 0 ? lblPreview.getWidth() : 150;
        int h = lblPreview.getHeight() > 0 ? lblPreview.getHeight() : 150;
        
        java.awt.Image scaledImg = img.getScaledInstance(w, h, java.awt.Image.SCALE_SMOOTH);
        lblPreview.setIcon(new ImageIcon(scaledImg));
        lblPreview.setText(""); 

    } catch (Exception e) {
        lblPreview.setIcon(null);
        lblPreview.setText("");
    }
}
    
    private void resetForm() {
        txtTitle.setText("");
        txtMessage.setText("");
        currentImagePath = "";
        selectedId = -1;
        jTable1.clearSelection();
        lblPreview.setIcon(null);
        lblPreview.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPreview;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
