/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL.view;

import BTL.bussiness.ProductsDao;
import BTL.entity.ComboItem;
import BTL.entity.Products;
import BTL.connect.MyConnection;
import java.sql.*;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProductForm extends javax.swing.JPanel {

    private DefaultTableModel tblModel;
    // 1. Khai báo DAO
    private final ProductsDao productsDao = new ProductsDao();

    public ProductForm() {
        initComponents();
        txtMota.setLineWrap(true);       // Tự động xuống dòng
        txtMota.setWrapStyleWord(true);
        // Setup ban đầu
        cbLoai.setModel(new DefaultComboBoxModel<>());
        cbThuonghieu.setModel(new DefaultComboBoxModel<>());
        cbNsx.setModel(new DefaultComboBoxModel<>());

        initTable();
        // Không cần gọi loadDataToTable() ở đây nữa vì sự kiện bên dưới sẽ lo việc đó
        // loadComboBoxes(); 
        // loadDataToTable(); 
        setupEvents();

    }
    // Hàm này làm mới toàn bộ dữ liệu (Public để bên ngoài gọi được nếu cần)
    public void refreshData() {
        // 1. Xóa trắng các ô nhập
        txtTensp.setText("");
        txtGia.setText("");
        txtSoluong.setText("");
        txtMota.setText("");
        txtSearch.setText("");
        
        // 2. Load lại ComboBox (Đề phòng có danh mục mới thêm bên kia)
        loadComboBoxes(); 
        
        // 3. Reset ComboBox về phần tử đầu
        if (cbLoai.getItemCount() > 0) cbLoai.setSelectedIndex(0);
        if (cbThuonghieu.getItemCount() > 0) cbThuonghieu.setSelectedIndex(0);
        if (cbNsx.getItemCount() > 0) cbNsx.setSelectedIndex(0);
        
        // 4. Load lại bảng từ Database
        loadDataToTable();
        
        // 5. Reset các trạng thái khác
        jLabel1.setText("Quản lí sản phẩm");
        jTable1.clearSelection();
    }

  

    private void initTable() {
        tblModel = new DefaultTableModel(
            new String[]{"ID", "Tên SP", "Giá", "Số lượng", "Danh mục", "Thương hiệu", "NSX", "Mô tả"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        jTable1.setModel(tblModel);
    }

    private void setupEvents() {
        // Tìm kiếm ngay khi gõ
        txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { searchData(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { searchData(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { searchData(); }
        });

        // Click bảng đổ dữ liệu lên Form
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) { bindingData(); }
        });
    }

    // --- CÁC HÀM LOAD DỮ LIỆU DÙNG DAO ---

    private void loadDataToTable() {
        List<Products> list = productsDao.getall();
        fillTable(list);
    }

    private void searchData() {
        String keyword = txtSearch.getText().trim();
        List<Products> list = productsDao.search(keyword);
        fillTable(list);
    }

    // Hàm này được gọi từ HomePage
    public void filterByCategory(int categoryId, String categoryName) {
        jLabel1.setText("Danh mục: " + categoryName);
        
        // Gọi DAO lấy list theo danh mục
        List<Products> list = productsDao.getByCategory(categoryId);
        fillTable(list);

        // Chọn sẵn ComboBox
        setSelectedComboItem(cbLoai, categoryName);
    }

    // --- HÀM HELPER: ĐỔ DỮ LIỆU RA BẢNG ---
    // Hàm này giúp chuyển đổi ID (từ DAO) thành Tên (lấy từ ComboBox) để hiện lên bảng
    private void fillTable(List<Products> list) {
        tblModel.setRowCount(0);
        for (Products p : list) {
            // "Mẹo": Lấy tên từ ComboBox dựa vào ID
            String catName = getComboNameById(cbLoai, p.getCategoryId());
            String brandName = getComboNameById(cbThuonghieu, p.getBrandId());
            String supName = getComboNameById(cbNsx, p.getSupplierId());

            tblModel.addRow(new Object[]{
                p.getProductId(),
                p.getName(),
                p.getPrice(),
                p.getStockQuantity(),
                catName,    // Hiện Tên
                brandName,  // Hiện Tên
                supName,    // Hiện Tên
                p.getDescription()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTensp = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnRf = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        cbLoai = new javax.swing.JComboBox<>();
        cbThuonghieu = new javax.swing.JComboBox<>();
        cbNsx = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí sản phẩm");

        jLabel2.setText("Tên sản phẩm");

        jLabel3.setText("Loại sản phẩm");

        jLabel4.setText("Thương hiệu");

        jLabel5.setText("Giá bán");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Nhà sản xuất");

        jLabel8.setText("Mô tả");

        btnRf.setText("Làm mới");
        btnRf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRfActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbThuonghieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbNsx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Tìm kiếm");

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane2.setViewportView(txtMota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbThuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGia)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbNsx, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(cbNsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(cbThuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRf)
                            .addComponent(btnSua)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnThem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfActionPerformed
        refreshData();
    }//GEN-LAST:event_btnRfActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần sửa!");
            return;
        }
        
        Products p = getFormInput();
        if (p != null) {
            // Lấy ID từ bảng gán vào đối tượng
            int id = Integer.parseInt(tblModel.getValueAt(row, 0).toString());
            p.setProductId(id);
            
            if (productsDao.update(p)) {
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
                btnRf.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại!");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần xóa!");
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Xóa sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(tblModel.getValueAt(row, 0).toString());
            if (productsDao.delete(id)) {
                JOptionPane.showMessageDialog(this, "Đã xóa!");
                btnRf.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        Products p = getFormInput(); // Lấy dữ liệu
        if (p != null) {
            if (productsDao.insert(p) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                btnRf.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtMotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotaActionPerformed

    private Products getFormInput() {
        String ten = txtTensp.getText().trim();
        if (ten.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập tên sản phẩm đi!");
            return null;
        }
        try {
            double gia = Double.parseDouble(txtGia.getText().trim());
            int sl = Integer.parseInt(txtSoluong.getText().trim());
            
            int catId = ((ComboItem) cbLoai.getSelectedItem()).getId();
            int brandId = ((ComboItem) cbThuonghieu.getSelectedItem()).getId();
            int supId = ((ComboItem) cbNsx.getSelectedItem()).getId();
            
            // ID tạm để 0
            return new Products(0, ten, catId, brandId, supId, gia, sl, txtMota.getText(), "");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá và Số lượng phải là số!");
            return null;
        }
    }

    // 2. Binding Data (Click bảng -> Form)
    private void bindingData() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            txtTensp.setText(tblModel.getValueAt(row, 1).toString());
            txtGia.setText(tblModel.getValueAt(row, 2).toString());
            txtSoluong.setText(tblModel.getValueAt(row, 3).toString());
            
            // Chọn ComboBox theo TÊN hiển thị trên bảng
            setSelectedComboItem(cbLoai, tblModel.getValueAt(row, 4).toString());
            setSelectedComboItem(cbThuonghieu, tblModel.getValueAt(row, 5).toString());
            setSelectedComboItem(cbNsx, tblModel.getValueAt(row, 6).toString());
            
            txtMota.setText(tblModel.getValueAt(row, 7).toString());
        }
    }

    // 3. Load ComboBox (Giữ nguyên SQL vì chưa có DAO cho các bảng phụ)
    private void loadComboBoxes() {
        try {
            Connection conn = MyConnection.getInstance().getConnection();
            Statement st = conn.createStatement();

            fillCombo(st, cbLoai, "SELECT category_id, name FROM categories", "category_id");
            fillCombo(st, cbThuonghieu, "SELECT brand_id, name FROM brands", "brand_id");
            fillCombo(st, cbNsx, "SELECT supplier_id, name FROM suppliers", "supplier_id");
            
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void fillCombo(Statement st, JComboBox cb, String sql, String idCol) throws SQLException {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb.getModel();
        model.removeAllElements();
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()) {
            model.addElement(new ComboItem(rs.getInt(idCol), rs.getString("name")));
        }
    }

    // 4. Chọn ComboBox theo tên
    private void setSelectedComboItem(JComboBox cb, String nameToSelect) {
        for (int i = 0; i < cb.getItemCount(); i++) {
            if (cb.getItemAt(i).toString().equalsIgnoreCase(nameToSelect)) {
                cb.setSelectedIndex(i); return;
            }
        }
    }
    
    // 5. [QUAN TRỌNG] Lấy Tên từ ComboBox bằng ID (để hiển thị lên bảng)
    private String getComboNameById(JComboBox cb, int id) {
        for (int i = 0; i < cb.getItemCount(); i++) {
            ComboItem item = (ComboItem) cb.getItemAt(i);
            if (item.getId() == id) return item.getName();
        }
        return "Unknown";
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // Thêm dòng này
        System.out.println("Đã click vào dòng: " + jTable1.getSelectedRow());

        bindingData(); // Hàm xử lý của bạn
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRf;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoai;
    private javax.swing.JComboBox<String> cbNsx;
    private javax.swing.JComboBox<String> cbThuonghieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables
}
