/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BTL.view;

import BTL.entity.Session; // Theo import mới của mày
import BTL.connect.MyConnection;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class ShopForm extends javax.swing.JPanel { // CHUẨN: Kế thừa JPanel

   DefaultTableModel model;
   private CustomersForm customersForm;
    public ShopForm(CustomersForm customersForm) {
        initComponents();
        this.customersForm= customersForm;
        setupTable();      // 1. Cấu hình cột
        loadDataToTable(""); // 2. Đổ dữ liệu
        setupSearch();     // 3. Tìm kiếm
    }
    
    // Constructor hỗ trợ lọc từ HomePage
    public ShopForm(String categoryName) {
        initComponents();
        setupTable();
        txtTimkiem.setText(categoryName);
        loadDataToTable(categoryName);
        setupSearch();
    }

    private void setupTable() {
        // Thứ tự các cột: 0: ID, 1: Tên SP, 2: Thể loại, 3: Giá, 4: Còn lại, 5: Mô tả
        String[] headers = {"ID", "Tên Sản Phẩm", "Thể loại", "Giá (VND)", "Còn lại", "Mô tả"};
        model = new DefaultTableModel(headers, 0) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        jTable1.setModel(model);

        // Ẩn cột ID (Index 0) để giao diện đẹp nhưng vẫn lấy được ID để mua hàng
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    private void loadDataToTable(String keyword) {
        model.setRowCount(0);
        
        // SQL JOIN: Lấy p.name (Tên SP) và c.name (Tên thể loại)
        String sql = "SELECT p.product_id, p.name, c.name AS category_name, p.price, p.stock_quantity, p.description " +
                     "FROM products p " +
                     "JOIN categories c ON p.category_id = c.category_id " +
                     "WHERE p.name LIKE ? OR c.name LIKE ?";

        try (Connection conn = MyConnection.getInstance().getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {
            
            String search = "%" + keyword.trim() + "%";
            pst.setString(1, search);
            pst.setString(2, search);

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                // PHẢI KHỚP VỚI THỨ TỰ HEADERS Ở TRÊN
                row.add(rs.getInt("product_id"));       // Index 0
                row.add(rs.getString("name"));             // Index 1
                row.add(rs.getString("category_name"));    // Index 2
                row.add(rs.getBigDecimal("price"));        // Index 3
                row.add(rs.getInt("stock_quantity"));      // Index 4
                row.add(rs.getString("description"));       // Index 5
                
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi load bảng: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        txtTimkiem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 0));
        jLabel1.setText("Sản Phẩm");

        btnThem.setText("Thêm vào giỏ hàng");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnThem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnThem)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // 1. LẤY ID TỪ KHO SESSION (Đã sửa lại chỗ này)

        int currentUserId = Session.userId;

        // Kiểm tra xem đã đăng nhập chưa
        if (currentUserId == 0) {

            JOptionPane.showMessageDialog(this, "Bạn chưa đăng nhập! Không thể mua hàng.");

            return;

        }

        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm!");

            return;

        }

        int productId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        String productName = jTable1.getValueAt(selectedRow, 1).toString();

        int stock = (int) Double.parseDouble(jTable1.getValueAt(selectedRow, 3).toString());

        if (stock <= 0) {

            JOptionPane.showMessageDialog(this, "Hết hàng rồi!");

            return;

        }

        try {

            Connection conn = MyConnection.getInstance().getConnection();

            // 2. Kiểm tra DB
            String checkSql = "SELECT quantity FROM cart WHERE user_id = ? AND product_id = ?";

            PreparedStatement checkPst = conn.prepareStatement(checkSql);

            checkPst.setInt(1, currentUserId); // Dùng ID lấy từ Session

            checkPst.setInt(2, productId);

            ResultSet rs = checkPst.executeQuery();

            if (rs.next()) {

                String updateSql = "UPDATE cart SET quantity = quantity + 1 WHERE user_id = ? AND product_id = ?";

                PreparedStatement updatePst = conn.prepareStatement(updateSql);

                updatePst.setInt(1, currentUserId);

                updatePst.setInt(2, productId);

                updatePst.executeUpdate();

            } else {

                String insertSql = "INSERT INTO cart(user_id, product_id, quantity) VALUES (?, ?, ?)";

                PreparedStatement insertPst = conn.prepareStatement(insertSql);

                insertPst.setInt(1, currentUserId);

                insertPst.setInt(2, productId);

                insertPst.setInt(3, 1);

                insertPst.executeUpdate();

            }

            JOptionPane.showMessageDialog(this, "Đã thêm '" + productName + "' vào giỏ hàng!");

        } catch (Exception e) {

            e.printStackTrace();

            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void setupSearch() {
        txtTimkiem.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { loadDataToTable(txtTimkiem.getText()); }
            public void removeUpdate(DocumentEvent e) { loadDataToTable(txtTimkiem.getText()); }
            public void changedUpdate(DocumentEvent e) { loadDataToTable(txtTimkiem.getText()); }
        });
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
