/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;

import BTL.bussiness.UsersDao;
import BTL.entity.Users;
import BTL.verify.EmailVerify;
import BTL.verify.NumberVerify;
import BTL.verify.StringVerify;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vanminh
 */
public class StaffCRUD extends javax.swing.JPanel {
    
    private DefaultTableModel tableModel;
    private final UsersDao usersDao = new UsersDao();
    private TableRowSorter<DefaultTableModel> rowSorter;
    private final MainForm mainForm;
    public StaffCRUD(MainForm mainForm) {
        initComponents();
        txtName.setInputVerifier(new StringVerify());
        txtPhone.setInputVerifier(new NumberVerify());
        txtEmail.setInputVerifier(new EmailVerify());
        this.mainForm = mainForm;
        initCustom();
    }
    private void initCustom() {
        tableModel = (DefaultTableModel) tblStaff.getModel();
        tableModel.setColumnIdentifiers(new Object[]{"ID", "Họ Tên", "Email", "Số ĐT", "Địa chỉ", "Giới tính"});
        rowSorter = new TableRowSorter<>(tableModel);
        tblStaff.setRowSorter(rowSorter);
        cbxAddress.setModel(new DefaultComboBoxModel<>(new String[] { 
            "Hà Nội", "Nam Định", "Thái Bình", "Ninh Bình", "Hải Phòng", 
            "Đà Nẵng", "TP. Hồ Chí Minh", "Cần Thơ", "Thanh Hóa", "Nghệ An", 
            "Quảng Ninh", "Lào Cai", "Huế", "Khánh Hòa", "Lâm Đồng" 
        }));
        cbxSearch.setModel(new DefaultComboBoxModel<>(new String[] { 
            "Tất cả", "Tên", "Email", "Số điện thoại" 
        }));

        loadData();
        setupSearchEvent();
    }
    private void loadData() {
        tableModel.setRowCount(0);
        usersDao.getall().forEach(u -> {
            if ("staff".equalsIgnoreCase(u.getRole())) {
                tableModel.addRow(new Object[]{
                    u.getUserId(), u.getFullName(), u.getEmail(), 
                    u.getPhoneNumber(), u.getAddress(), u.getGender()
                });
            }
        });
    }

    private String getSelectedGender() {
        if (rbtNam.isSelected()) return "Nam";
        if (rbtNu.isSelected()) return "Nữ";
        if (rbtKhac.isSelected()) return "Khác";
        return "Khác";
    }

    private void setupSearchEvent() {
        txtSearch.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { search(); }
            public void removeUpdate(DocumentEvent e) { search(); }
            public void changedUpdate(DocumentEvent e) { search(); }          
        });
        cbxSearch.addActionListener(e -> search());
    }
    private void search() {
                String text = txtSearch.getText();
                // Lấy vị trí mục đang chọn trong ComboBox (0: Tất cả, 1: Tên, 2: Email, 3: SĐT)
                int selectedIndex = cbxSearch.getSelectedIndex(); 

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    String pattern = "(?i)" + text;

                    if (selectedIndex == 0) {
                        rowSorter.setRowFilter(RowFilter.regexFilter(pattern));
                    } else {
                        rowSorter.setRowFilter(RowFilter.regexFilter(pattern, selectedIndex));
                    }
                }
            }
    public void reset(){
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        cbxAddress.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        tblStaff.clearSelection();
        loadData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxAddress = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        rbtKhac = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnLamMoiNV = new javax.swing.JButton();
        cbxSearch = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 600));

        tblStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStaff.getColumnModel().getColumn(0).setPreferredWidth(0);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Phone :");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("Address :");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Gender :");

        buttonGroup1.add(rbtNam);
        rbtNam.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbtNam.setText("Nam");

        buttonGroup1.add(rbtNu);
        rbtNu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbtNu.setText("Nữ");

        buttonGroup1.add(rbtKhac);
        rbtKhac.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rbtKhac.setText("Khác");

        btnThemNV.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.setFocusPainted(false);
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnSuaNV.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.setFocusPainted(false);
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        btnXoaNV.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.setFocusPainted(false);
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnLamMoiNV.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnLamMoiNV.setText("Làm mới");
        btnLamMoiNV.setFocusPainted(false);
        btnLamMoiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiNVActionPerformed(evt);
            }
        });

        cbxSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setText("Nhập :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtEmail)
                    .addComponent(txtPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtNam)
                        .addGap(18, 18, 18)
                        .addComponent(rbtNu)
                        .addGap(18, 18, 18)
                        .addComponent(rbtKhac))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cbxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnThemNV)
                        .addGap(60, 60, 60)
                        .addComponent(btnSuaNV)
                        .addGap(52, 52, 52)
                        .addComponent(btnXoaNV)
                        .addGap(47, 47, 47)
                        .addComponent(btnLamMoiNV))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtNam)
                            .addComponent(rbtNu)
                            .addComponent(rbtKhac))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnSuaNV)
                    .addComponent(btnXoaNV)
                    .addComponent(btnLamMoiNV))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String address = cbxAddress.getSelectedItem().toString();
        
        if (name.isEmpty() || email.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ các thông tin bắt buộc!");
            return;
        }
        else if (usersDao.get(email).isPresent()) {
            JOptionPane.showMessageDialog(this, "Email này đã được sử dụng, vui lòng chọn email khác!");
            txtEmail.requestFocus();
            return;
        }

        Users u = Users.createStaff(
            0, 
            txtName.getText().trim(), 
            txtEmail.getText().trim(), 
            null,
            txtPhone.getText().trim(), 
            cbxAddress.getSelectedItem().toString(), 
            getSelectedGender()
        );

        if (usersDao.insert(u) > 0) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công! (Mật khẩu mặc định: 123456)");
            loadData();
            btnLamMoiNVActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại. Vui lòng kiểm tra lại kết nối!");
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        String email = txtEmail.getText().trim();

        int row = tblStaff.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần sửa trên bảng!");
            return;
        }
        int id = Integer.parseInt(tblStaff.getValueAt(row, 0).toString());
        Optional<Users> userNhanDuoc = usersDao.get(email); 

        if (userNhanDuoc.isPresent()) {
            if (userNhanDuoc.get().getUserId() != id) {
                JOptionPane.showMessageDialog(this, "Email này đã được sử dụng bởi một nhân viên khác!");
                txtEmail.requestFocus();
                return;
            }
        }
        
        Users u = Users.createStaff(
            id, 
            txtName.getText().trim(), 
            txtEmail.getText().trim(), 
            null, 
            txtPhone.getText().trim(), 
            cbxAddress.getSelectedItem().toString(), 
            getSelectedGender()
        );
        
        if (usersDao.update(u)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thông tin thành công!");
            loadData();
            btnLamMoiNVActionPerformed(null);
        }else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại. Vui lòng kiểm tra lại kết nối!");
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        // TODO add your handling code here:
        int row = tblStaff.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên trên bảng để xóa!");
            return;
        }
        if (row != -1) {
            int id = Integer.parseInt(tblStaff.getValueAt(row, 0).toString());
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa nhân viên ID: " + id + "?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                usersDao.delete(id);
                loadData();
                btnLamMoiNVActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnLamMoiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiNVActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtEmail.setText("");
        txtPhone.setText("");
        cbxAddress.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        tblStaff.clearSelection();
        loadData();
    }//GEN-LAST:event_btnLamMoiNVActionPerformed

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
        // TODO add your handling code here:
        int row = tblStaff.getSelectedRow();
        if (row != -1) {
            int modelRow = tblStaff.convertRowIndexToModel(row);
            txtName.setText(tableModel.getValueAt(modelRow, 1).toString());
            txtEmail.setText(tableModel.getValueAt(modelRow, 2).toString());
            txtPhone.setText(tableModel.getValueAt(modelRow, 3).toString());
            String address = tableModel.getValueAt(modelRow, 4).toString();
            cbxAddress.setSelectedItem(address);
            String gender = tableModel.getValueAt(modelRow, 5).toString();
            if ("Nam".equalsIgnoreCase(gender)) {
                rbtNam.setSelected(true);
            } else if ("Nữ".equalsIgnoreCase(gender)) {
                rbtNu.setSelected(true);
            } else {
                rbtKhac.setSelected(true);
            }
            
            System.out.println("Đã chọn nhân viên ID: " + tableModel.getValueAt(modelRow, 0));
        }
    }//GEN-LAST:event_tblStaffMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxAddress;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtKhac;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
