/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;
import BTL.bussiness.StatisticalDao;
import BTL.entity.Orders;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Administrator
 */
public class StatisticalCRUD extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private final StatisticalDao dao = new StatisticalDao();
    /**
     * Creates new form StatisticalCRUD
     */
    private final MainForm mainForm;
    public StatisticalCRUD(MainForm mainForm) {
        initComponents();
        this.mainForm= mainForm;
        ButtonGroup group = new ButtonGroup();
        group.add(Ngay);
        group.add(Thang);
        group.add(Nam);
        Ngay.setSelected(true); 
        updateRadioState();
        initTable();       
        lblTongHoaDonValue.setText("0");
        lblTongDoanhThuValue.setText("0 VNĐ");
    }
    public void reset(){
        Ngay.setEnabled(true);
        Thang.setEnabled(true);
        Nam.setEnabled(true);
        Ngay.setSelected(true);
        spnngay.setSelectedIndex(0);
        spnthang.setSelectedIndex(0);
        spnnam.setValue(2020); 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        lblTongHoaDonValue.setText("0");
        lblTongDoanhThuValue.setText("0 VNĐ");
        updateRadioState();
    }
    
    private void initTable() {
        // Định nghĩa đúng 4 cột: ID, Thời gian, Trạng thái, Doanh thu
        String[] columns = {"ID Hóa đơn", "Thời gian", "Trạng thái", "Doanh thu"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Không cho sửa trực tiếp trên bảng
            }
        };
        jTable1.setModel(tableModel);
    }
    
    private void updateRadioState() {
    Ngay.setEnabled(true);
    Thang.setEnabled(true);
    Nam.setEnabled(true);

    if (Ngay.isSelected()) {
        
        Thang.setEnabled(true);
        Nam.setEnabled(true);
        
        
        spnngay.setEnabled(true);
        spnthang.setEnabled(true);
        spnnam.setEnabled(true);
    } 
    else if (Thang.isSelected()) {
        
        Ngay.setEnabled(false);
        Nam.setEnabled(true);
        
        spnngay.setEnabled(false);
        spnthang.setEnabled(true);
        spnnam.setEnabled(true);
    } 
    else if (Nam.isSelected()) {
        
        Ngay.setEnabled(false);
        Thang.setEnabled(false);
        
        spnngay.setEnabled(false);
        spnthang.setEnabled(false);
        spnnam.setEnabled(true);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnngay = new javax.swing.JComboBox<>();
        spnthang = new javax.swing.JComboBox<>();
        Ngay = new javax.swing.JRadioButton();
        Thang = new javax.swing.JRadioButton();
        Nam = new javax.swing.JRadioButton();
        btnTimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnnam = new javax.swing.JSpinner();
        lblTongHoaDonValue = new javax.swing.JLabel();
        lblTongDoanhThuValue = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Doanh thu");

        spnngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        spnngay.addActionListener(this::spnngayActionPerformed);

        spnthang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        Ngay.setText("Ngày");
        Ngay.addActionListener(this::NgayActionPerformed);

        Thang.setText("Tháng");
        Thang.setActionCommand("");
        Thang.addActionListener(this::ThangActionPerformed);

        Nam.setText("Năm");
        Nam.setActionCommand("");
        Nam.addActionListener(this::NamActionPerformed);

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(this::btnTimkiemActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tổng hoá đơn :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tổng doanh thu :");

        spnnam.setModel(new javax.swing.SpinnerNumberModel(2020, 2020, 2026, 1));
        spnnam.setEditor(new javax.swing.JSpinner.NumberEditor(spnnam, "#"));

        lblTongHoaDonValue.setText("jLabel4");

        lblTongDoanhThuValue.setText("jLabel5");

        btnReset.setText("Làm mới");
        btnReset.addActionListener(this::btnResetActionPerformed);

        jLabel4.setText("Thống kê theo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblTongHoaDonValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(lblTongDoanhThuValue)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ngay)
                                    .addComponent(spnngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(btnTimkiem)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(spnnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Thang)
                                        .addGap(50, 50, 50)
                                        .addComponent(Nam))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnReset))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ngay)
                    .addComponent(Thang)
                    .addComponent(jLabel4)
                    .addComponent(Nam))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimkiem)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblTongHoaDonValue)
                    .addComponent(lblTongDoanhThuValue))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void spnngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spnngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spnngayActionPerformed

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        // TODO add your handling code here:
    String type = Ngay.isSelected() ? "Ngay" : (Thang.isSelected() ? "Thang" : "Nam");
    
    int d = Integer.parseInt(spnngay.getSelectedItem().toString());
    int m = Integer.parseInt(spnthang.getSelectedItem().toString());
    int y = (int) spnnam.getValue();

    List<Orders> list = dao.getFiltered(type, d, m, y);
    if (list == null || list.isEmpty()) {
        tableModel.setRowCount(0); // Xóa bảng cho sạch
        lblTongHoaDonValue.setText("0");
        lblTongDoanhThuValue.setText("0 VNĐ");
        JOptionPane.showMessageDialog(this, "Không có hóa đơn nào trong thời gian này!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return; // Dừng luôn không chạy code bên dưới nữa
    }
    tableModel.setRowCount(0); 
    
    double totalRevenue = 0; 
    int countDelivered = 0;  

    for (Orders o : list) {       
        tableModel.addRow(new Object[]{
            o.getOrderId(),
            o.getCreatedAt(),
            o.getStatus(), 
            String.format("%,.0f VNĐ", o.getTotalAmount())
        });     
        if (o.getStatus() != null && o.getStatus().equalsIgnoreCase("delivered")) {
            totalRevenue += o.getTotalAmount();
            countDelivered++;
        }
    }  
    lblTongHoaDonValue.setText(String.valueOf(list.size()));     
    lblTongDoanhThuValue.setText(String.format("%,.0f VNĐ", totalRevenue));
    
    
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void NgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgayActionPerformed
        // TODO add your handling code here:
        updateRadioState();
    }//GEN-LAST:event_NgayActionPerformed

    private void ThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThangActionPerformed
        // TODO add your handling code here:
        updateRadioState();
    }//GEN-LAST:event_ThangActionPerformed

    private void NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamActionPerformed
        // TODO add your handling code here:
        updateRadioState();
    }//GEN-LAST:event_NamActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    Ngay.setEnabled(true);
    Thang.setEnabled(true);
    Nam.setEnabled(true);
    Ngay.setSelected(true);
    spnngay.setSelectedIndex(0);
    spnthang.setSelectedIndex(0);
    spnnam.setValue(2020); 
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    lblTongHoaDonValue.setText("0");
    lblTongDoanhThuValue.setText("0 VNĐ");
    updateRadioState();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Nam;
    private javax.swing.JRadioButton Ngay;
    private javax.swing.JRadioButton Thang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTongDoanhThuValue;
    private javax.swing.JLabel lblTongHoaDonValue;
    private javax.swing.JSpinner spnnam;
    private javax.swing.JComboBox<String> spnngay;
    private javax.swing.JComboBox<String> spnthang;
    // End of variables declaration//GEN-END:variables
}
