/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BTL.view;
import BTL.bussiness.NotificationDao;
import BTL.entity.Notification;
import java.awt.*;
import java.util.List;
import javax.swing.*;
/**
 *
 * @author Administrator
 */
public class TrangchuCRUD extends javax.swing.JPanel {
    private final NotificationDao dao = new NotificationDao();
    private CustomersForm customersForm;
    /**
     * Creates new form TrangchuCRUD
     */
    public TrangchuCRUD(CustomersForm customersForm) {
        initComponents();
        this.customersForm = customersForm;
        showNewsFeed();
        txtThongbao.setEnabled(false);
    }
    private void showNewsFeed() {
        // 1. Tạo Model để chứa dữ liệu đối tượng Notification
        DefaultListModel<Notification> model = new DefaultListModel<>();
        List<Notification> list = dao.getall();
        if (list != null) {
            for (Notification n : list) {
                model.addElement(n);
            }
        }
        listThongBao.setModel(model);

        // 2. Định dạng cách hiển thị (Renderer)
        listThongBao.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Notification n = (Notification) value;

                // Dùng HTML để chữ tự xuống dòng và định dạng màu sắc
                String html = "<html><body style='width: 350px; padding: 5px;'>"
                        + "<b style='font-size: 14px; color: #2C3E50;'>" + n.getTitle() + "</b><br>"
                        + "<i style='font-size: 10px; color: #7F8C8D;'>" + n.getCreatedAt() + "</i><br><br>"
                        + "<p style='font-size: 12px; color: #34495E;'>" + n.getMessage() + "</p>"
                        + "</body></html>";

                JLabel label = (JLabel) super.getListCellRendererComponent(list, html, index, isSelected, cellHasFocus);

                // Hiển thị ảnh Thumbnail
                if (n.getImage() != null && !n.getImage().isEmpty()) {
                    try {
                        ImageIcon icon = new ImageIcon(new ImageIcon(n.getImage()).getImage()
                                .getScaledInstance(100, 100, Image.SCALE_SMOOTH));
                        label.setIcon(icon);
                    } catch (Exception e) {
                        label.setIcon(null);
                    }
                } else {
                    label.setIcon(null);
                }

                label.setIconTextGap(20); 
                label.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.LIGHT_GRAY)); 
                
                // Đổi màu nền khi được chọn cho đẹp
                if (isSelected) {
                    label.setBackground(new Color(236, 240, 241));
                } else {
                    label.setBackground(Color.WHITE);
                }
                
                return label;
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listThongBao = new javax.swing.JList<>();
        txtTitle = new javax.swing.JTextField();
        txtThongbao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        listThongBao.setModel(new DefaultListModel<Notification>());
        jScrollPane2.setViewportView(listThongBao);

        txtTitle.setBackground(new java.awt.Color(255, 255, 0));
        txtTitle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(255, 0, 0));
        txtTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitle.setText("Cửa hàng máy tính Cường Thuận");

        txtThongbao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtThongbao.setForeground(new java.awt.Color(51, 0, 51));
        txtThongbao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtThongbao.setText("Thông Báo");
        txtThongbao.addActionListener(this::txtThongbaoActionPerformed);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vanminh\\Downloads\\he-thong-giao-thong-thong-minh-its.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtTitle)
            .addComponent(txtThongbao, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtThongbao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtThongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThongbaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThongbaoActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Notification> listThongBao;
    private javax.swing.JTextField txtThongbao;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
